//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayerTest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IPSEntities : DbContext
    {
        public IPSEntities()
            : base("name=IPSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KameraParkplatzSet> KameraParkplatzSets { get; set; }
        public virtual DbSet<KameraSet> KameraSets { get; set; }
        public virtual DbSet<ParkplatzartSet> ParkplatzartSets { get; set; }
        public virtual DbSet<ParkplatzSet> ParkplatzSets { get; set; }
        public virtual DbSet<ReservierungSet> ReservierungSets { get; set; }
    }
}
