//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayerTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class KameraParkplatzSet
    {
        public int Id { get; set; }
        public int Kamera_Id { get; set; }
        public int Parkplatz_Id { get; set; }
    
        public virtual KameraSet KameraSet { get; set; }
        public virtual ParkplatzSet ParkplatzSet { get; set; }
    }
}
