//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayerTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParkplatzSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ParkplatzSet()
        {
            this.KameraParkplatzSets = new HashSet<KameraParkplatzSet>();
            this.ReservierungSets = new HashSet<ReservierungSet>();
        }
    
        public int Id { get; set; }
        public int Nummer { get; set; }
        public string Name { get; set; }
        public int Etage { get; set; }
        public int Parkplatzart_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KameraParkplatzSet> KameraParkplatzSets { get; set; }
        public virtual ParkplatzartSet ParkplatzartSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservierungSet> ReservierungSets { get; set; }
    }
}
