//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IPSEntities : DbContext
    {
        public IPSEntities()
            : base("name=IPSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KameraParkplatzSet> KameraParkplatzSets { get; set; }
        public virtual DbSet<KameraSet> KameraSets { get; set; }
        public virtual DbSet<ParkplatzartSet> ParkplatzartSets { get; set; }
        public virtual DbSet<ParkplatzSet> ParkplatzSets { get; set; }
        public virtual DbSet<ReservierungSet> ReservierungSets { get; set; }
    }
}
