//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservierungSet
    {
        public int Id { get; set; }
        public System.DateTime Datum { get; set; }
        public string User { get; set; }
        public string Nummernschild { get; set; }
        public int Parkplatz_Id { get; set; }
    
        public virtual ParkplatzSet ParkplatzSet { get; set; }
    }
}
